### ISSUE TITLE
학사 일정 API

### ISSUE THREAD

**Issue by developerChans** [DKUcouncilhomepage/student-council-homepage-backend#125]
학사일정 크롤링하여 데이터 업데이트해야할 것 같음

**Comment by developerChans** [comment]
회의록, 회칙, 총학소식 데이터 다시 옮겨줘야할 것 같음.

**Comment by won983212** [comment]
> 회의록, 회칙, 총학소식 데이터 다시 옮겨줘야할 것 같음.

This comment moved to #151
