### ISSUE TITLE
버스 남은 시간 버그

### ISSUE THREAD

**Issue by chocojaem** [DKUcouncilhomepage/student-council-homepage-backend#154]
- 곰상이랑 정문 버스 시간 똑같은 버그 수정 필요

-  ~~자유게시판 댓글 닉네임이랑 자신꺼인지 알 수 있는 Mine(?) DTO에 담아줘~~

**Comment by won983212** [comment]
> 자유게시판 댓글 닉네임이랑 자신꺼인지 알 수 있는 Mine(?) DTO에 담아줘
Moved to #163
