### ISSUE TITLE
자유게시판 리스트 DTO 문제점

### ISSUE THREAD

**Issue by chocojaem** [DKUcouncilhomepage/student-council-homepage-backend#163]
청원 게시판 좋아요 수 DTO에서 제외 하면서 잘못 건들여서 자유게시판 부분도 같이 삭제 한듯? 자유게시판 리스트 좋아요 표시 안됨. 단건 조회는 됨

**Comment by chocojaem** [comment]
{content: [{id: 44, title: ddfd, author: 공과대학 lee, body: <p>ddfs</p>
, createdAt: 2023-03-14, files: [], views: 1, commentCount: 6}, {id: 48, title: fjlkdasjfkdsajfkldsajkl  jklaj lklkdj fldajfldk fjdlk fjdlska jfdksl jlvk laj dasvdsf jfkdjfhdkjsafh, author: 공과대학 lee, body: <p>dsajfdlsajfkldsajfkl</p>
<p>dfsdjflkdsjf</p>
, createdAt: 2023-03-14, files: [], views: 3, commentCount: 1}], hasNext: false, totalPages: 1, totalElements: 2, page: 1, size: 5, first: true, last: true}

**Comment by won983212** [comment]
자유게시판 댓글 닉네임이랑 자신꺼인지 알 수 있는 Mine(?) DTO에 담아줘
