### ISSUE TITLE
기능 우선 순위 및 필요 구현 목록

### ISSUE THREAD

**Issue by chocojaem** [DKUcouncilhomepage/student-council-homepage-backend#164]
기능 우선순위 순으로 정렬

1. 청원 게시판 리 디자인 및 기능 재구성 -> 아마 디자인 나오면 DTO 수정만 나중에 해주면 될 거 같습니다
2. 시간표 추가 뷰 -> 시간표 유저에 추가할 수 있도록 엔티티 만들어야 할 것 같습니다. 그리고 강의정보 전체 가져올 수 있는 api 필요할 수 있습니다.
3. 아이디 / 비번찾기(휴대폰) -> 되는걸로 아는데 (로그아웃 안된다고 적혀있는데 고쳐야 합니다, 그리고 일단 로그인 정보로 학번, 이름, 과 가져오는데 user 정보 가져오는 api로도 다 불러올 수 있어야 합니다. 
현재는 DTO는 이렇게 받아집니다{
  "studentName": "이현",
  "yearOfAdmission": "2017",
  "major": "응용컴퓨터공학과"
})
4. 내가쓴 글, 댓글단 글, 좋아요한 글 표시 -> 이것도 마이페이지 접근하면(유저 정보 가져올때) DTO로 제공해줘야 합니다.
5. 신고 기능 -> 구현 가능한지 여부가 궁금합니다
6. 메인의 버튼 중 학교 홈 → 학식, (웹정보 → ? 변경) -> 이쪽은 백은 신경안써도 될 것 같습니다
7. 테마, 언어 지원 → 최대한 고려 -> 백엔드랑 관계없을 것 같습니다

**Comment by won983212** [comment]
### 다시 작업 목록만 정리

1. 청원 게시판 재구성
   - DTO만 수정될 것 같음
   - 댓글 자체가 없어질 가능성이 높음
1. 유저마다 시간표 필요 (CRUD)
1. 강의정보 전체 가져올 수 있는 API
1. 내가쓴 글, 댓글단 글, 좋아요한 글 API
1. 신고 기능

**Comment by chocojaem** [comment]
이전에 자유게시판 DTO 수정이랑, 버스 시간 곰상 정문 똑같은 버그 까지 포함

**Comment by won983212** [comment]
> 로그아웃 안된다고 적혀있는데 고쳐야 할듯

현재 로그인은 JWT 토큰 방식으로, 로그아웃은 구현되지 않을 예정. 향후 리소스가 좀 더 여유로워지면 in memory cache를 활용한 로그인으로 바꿀 예정이고 이때는 로그아웃을 포함한 외부 컴퓨터 로그인 기록 추적 등이 가능해짐.
결론은 아직까지 로그아웃 구현 계획 X (후순위)

> 그리고 일단 로그인 정보로 학번, 이름, 과 가져오는데 user 정보 가져오는 api로도 다 불러올 수 있어야함 지금은 이렇게만 줌

로그인 시 제공하는 사용자 정보는 뺄 예정. 사용자 정보를 얻기 위해서는 /user api call이 필요해짐. (api call은 겨우 1회 늘어나지만 확장성과 유지보수의 용이성을 따져봤을 때 이 방법이 더 효율적)

> 4. 내가쓴 글, 댓글단 글, 좋아요한 글 표시 -> 이것도 마이페이지 접근하면(유저 정보 가져올때) DTO로 제공해줘야함

글은 반드시 Paging이 필요하므로 /user api에서 통합해서 제공할 수 없음. 내 기록은 따로 api로 뺄 예정.

> 5. 신고 기능 -> 구현 가능?

기획이 정해지면 신고 기능도 구현할 수 있음

**Comment by won983212** [comment]
> 이전에 자유게시판 DTO 수정이랑, 버스 시간 곰상 정문 똑같은 버그 까지 포함

과거 Issue로 작성된 부분에 대해서는 추가 언급할 필요 없습니다.

반드시 언급이 필요한 경우에는 #154 와 같이 링크 첨부해주세요.
