### ISSUE TITLE
비밀번호 찾기 전화번호 만으로 찾기

### ISSUE THREAD

**Issue by chocojaem** [DKUcouncilhomepage/student-council-homepage-backend#183]
1. 댓글에 좋아요 표기 안되는데 댓글도 게시글처럼 좋아요 달 수 있어야합니다
2. 비밀번호 찾기 현재 학번, 전화번호 입력받아서 인증코드 보내는 식인데 전화번호 만으로 가능하게 부탁드립니다

**Comment by won983212** [comment]
> 댓글에 좋아요 표기 안되는데 댓글도 게시글처럼 좋아요 달 수 있어야함

전반적으로 설계를 다시 해야하므로 반영까지 시간이 걸릴 수 있습니다.

> 비밀번호 찾기 현재 학번, 전화번호 입력받아서 인증코드 보내는 식인데 전화번호 만으로 가능하게 부탁

수정 예정

**Comment by won983212** [comment]
> 댓글에 좋아요 표기 안되는데 댓글도 게시글처럼 좋아요 달 수 있어야합니다

댓글 좋아요 기능은 따로 issue 등록하겠습니다.

> 비밀번호 찾기 현재 학번, 전화번호 입력받아서 인증코드 보내는 식인데 전화번호 만으로 가능하게 부탁드립니다

이건 수정되었으므로 issue close하겠습니다.
