### ISSUE TITLE
청원게시판 agreeCount 오류

### ISSUE THREAD

**Issue by gaeunnlee** [DKUcouncilhomepage/student-council-homepage-backend#212]
![image](https://user-images.githubusercontent.com/88781949/229284720-f81e829c-9c3a-4a79-82ad-f4c7965704c4.png)
청원게시판의 총 동의 개수가 실제와 맞지 않습니다.

**Comment by won983212** [comment]
버그인 것 같습니다. 수정하겠습니다.

## 설계 Note

@YOONSEOUNGHWAN 

 - 기존에 작성한 동의 댓글은 Comment에 남아있지만, PetitionStatistics 테이블에 없어서 개수가 맞지 않는 것 처럼 나옵니다.
 - 이전에 작성한 Comment들만 지우면 문제는 해결됩니다. (단순 DB 일관성 문제)

하지만 향후 캐싱 및 의존성 최소화를 위해 구조를 약간 수정해야 할 것 같습니다.
 - 청원에서 댓글 의존성은 완전히 제거해주세요.
   - `PetitionController`에서 댓글 관련 API 모두 완전 삭제해주세요.
   - `동의 수 = 댓글 수`로 확인하는 로직이 아니라, PetitionStatistics에서 count를 통해 동의 수를 가져오도록 해야합니다.
